---
name: Build and Install Matrix

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-install:
    runs-on: ubuntu-latest  # GitHub-hosted runner
    strategy:
      matrix:
        container:
          - fedora-latest
    container:
      image: ghcr.io/agl4/init/${{ matrix.container }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run make install
        run: make install

      - name: Run test
        run: make test
