---
name: Build and Install Matrix

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-install:
    runs-on: ubuntu-latest  # GitHub-hosted runner
    strategy:
      matrix:
        container:
          - ghcr.io/agl4/init/fedora-latest
          - fedora:42
    container:
      image: ${{ matrix.container }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: |
          curl -fsSL https://raw.githubusercontent.com/agl4/init/refs/heads/main/bootstrap.sh | sh
        if: matrix.container == 'fedora:42'

      - name: Run make install
        run: make install

      - name: Run test
        run: make test
